# Generated by Django 4.1.7 on 2023-04-15 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_classroom_student_s_email_alter_student_studentid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='s_email',
            new_name='email',
        ),
    ]
