# Generated by Django 4.1.7 on 2023-05-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0007_alter_course_course_key_alter_student_studentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
