# Generated by Django 4.1.7 on 2023-09-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0009_classroom_seat_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='seat',
            field=models.IntegerField(default=0),
        ),
    ]
