# Generated by Django 4.1.7 on 2023-09-27 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0012_course_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_seat',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loginapp.classroom'),
        ),
    ]
