# Generated by Django 4.1.7 on 2023-10-15 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0014_remove_course_seat_classroom'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course_selection',
            unique_together={('course_key', 'studentID')},
        ),
    ]
