# Generated by Django 4.2.6 on 2023-10-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0016_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_seat',
            name='is_absent',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
