# Generated by Django 4.2.6 on 2023-10-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0017_course_seat_is_absent_delete_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='class_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
