# Generated by Django 4.2.6 on 2023-10-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0019_course_day_of_week_alter_course_class_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='class_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
