# Generated by Django 4.2.6 on 2023-11-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0020_alter_course_class_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_seat',
            name='selection_time',
            field=models.DateTimeField(null=True),
        ),
    ]
