# Generated by Django 4.2.6 on 2023-11-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0021_course_seat_selection_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
