# Generated by Django 4.2.6 on 2023-11-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0024_student_is_student_teacher_is_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_teacher',
            field=models.BooleanField(default=True),
        ),
    ]
