# Generated by Django 4.2.6 on 2023-11-02 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0026_alter_student_studentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.classroom', verbose_name='教室代碼'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_className',
            field=models.CharField(max_length=20, verbose_name='班別'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_grade',
            field=models.CharField(max_length=20, verbose_name='年級'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_key',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False, verbose_name='課程代碼'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=20, verbose_name='課程名稱'),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(max_length=20, verbose_name='科系'),
        ),
        migrations.AlterField(
            model_name='course',
            name='seat',
            field=models.IntegerField(default=0, verbose_name='座位'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.teacher', verbose_name='教師代碼'),
        ),
    ]
