# Generated by Django 4.2.6 on 2023-11-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0034_alter_course_options_alter_course_seat_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': '教室', 'verbose_name_plural': '教室列表'},
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='seat_ip',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='classroom_key',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='教室代碼'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='seat',
            field=models.IntegerField(default=0, verbose_name='座位'),
        ),
    ]
