# Generated by Django 4.1.7 on 2023-04-15 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_remove_student_id_alter_student_studentid'),
    ]

    operations = [
        migrations.CreateModel(
            name='classroom',
            fields=[
                ('classroom_key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('seat', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='s_email',
            field=models.EmailField(default=123456, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='studentID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('course_key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('teacher_key', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('course_grade', models.CharField(max_length=20)),
                ('course_className', models.CharField(max_length=20)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.classroom')),
            ],
        ),
    ]
