# Generated by Django 4.1.7 on 2023-04-15 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_rename_s_email_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=4)),
                ('job_title', models.CharField(max_length=5)),
                ('teacher_email', models.EmailField(default='12346', max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('seat', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('week_1', models.BooleanField()),
                ('student', models.ManyToManyField(to='loginapp.student')),
                ('teacher_key', models.ManyToManyField(to='loginapp.teacher')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.teacher'),
        ),
    ]
