# Generated by Django 4.2 on 2023-04-19 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0005_teacher_course_selection_alter_course_teacher_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_selection',
            name='student',
        ),
        migrations.RemoveField(
            model_name='course_selection',
            name='teacher_key',
        ),
        migrations.AddField(
            model_name='course_selection',
            name='course_key',
            field=models.ForeignKey(default=123456, on_delete=django.db.models.deletion.CASCADE, to='loginapp.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course_selection',
            name='studentID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='loginapp.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course_key',
            field=models.CharField(default='input', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentID',
            field=models.IntegerField(default='00000000', primary_key=True, serialize=False),
        ),
    ]
