# Generated by Django 4.1.7 on 2023-09-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0008_alter_student_studentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='seat_ip',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
