# Generated by Django 4.1.7 on 2023-09-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0010_alter_classroom_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='seat',
            field=models.IntegerField(default=0),
        ),
    ]
