# Generated by Django 4.1.7 on 2023-09-27 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0011_course_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_seat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=0)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.classroom')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.student')),
            ],
        ),
    ]
