# Generated by Django 4.1.7 on 2023-09-27 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0013_alter_course_seat_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_seat',
            name='classroom',
        ),
    ]
