# Generated by Django 4.2.6 on 2023-10-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0018_course_class_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='class_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
