# Generated by Django 4.1.7 on 2023-11-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0030_alter_teacher_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_seat',
            name='number',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
