# Generated by Django 4.2.6 on 2023-11-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0031_alter_course_seat_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '學生', 'verbose_name_plural': '學生列表'},
        ),
        migrations.AlterField(
            model_name='student',
            name='className',
            field=models.CharField(max_length=20, verbose_name='班級名稱'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=30, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=128, verbose_name='密碼'),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='學號'),
        ),
    ]
