# Generated by Django 4.2.6 on 2023-11-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0032_alter_student_options_alter_student_classname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '課程1', 'verbose_name_plural': '課程列表'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '老師', 'verbose_name_plural': '老師列表'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='job_title',
            field=models.CharField(max_length=5, verbose_name='職稱'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='123', max_length=128, verbose_name='密碼'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='電話'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='seat',
            field=models.CharField(max_length=20, verbose_name='研究室位置'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_email',
            field=models.EmailField(default='12346', max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_key',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='教師代碼'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_name',
            field=models.CharField(max_length=4, verbose_name='姓名'),
        ),
    ]
