# Generated by Django 4.2.6 on 2023-11-30 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0033_alter_course_options_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '課程', 'verbose_name_plural': '課程列表'},
        ),
        migrations.AlterModelOptions(
            name='course_seat',
            options={'verbose_name': '選課座位', 'verbose_name_plural': '選課座位列表'},
        ),
        migrations.AlterModelOptions(
            name='course_selection',
            options={'verbose_name': '課程選課', 'verbose_name_plural': '課程選課列表'},
        ),
        migrations.AlterField(
            model_name='course_seat',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.course', verbose_name='課程'),
        ),
        migrations.AlterField(
            model_name='course_seat',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='course_seat',
            name='is_absent',
            field=models.BooleanField(default=False, verbose_name='是否缺席'),
        ),
        migrations.AlterField(
            model_name='course_seat',
            name='number',
            field=models.IntegerField(default=0, null=True, verbose_name='座位號'),
        ),
        migrations.AlterField(
            model_name='course_seat',
            name='selection_time',
            field=models.DateTimeField(null=True, verbose_name='選課時間'),
        ),
        migrations.AlterField(
            model_name='course_seat',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.student', verbose_name='學生'),
        ),
        migrations.AlterField(
            model_name='course_seat',
            name='week_number',
            field=models.IntegerField(choices=[(1, '1周'), (2, '2周'), (3, '3周'), (4, '4周'), (5, '5周'), (6, '6周'), (7, '7周'), (8, '8周'), (9, '9周'), (10, '10周'), (11, '11周'), (12, '12周'), (13, '13周'), (14, '14周'), (15, '15周'), (16, '16周'), (17, '17周'), (18, '18周')], default=1, verbose_name='周數'),
        ),
        migrations.AlterField(
            model_name='course_selection',
            name='course_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.course', verbose_name='課程代碼'),
        ),
        migrations.AlterField(
            model_name='course_selection',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='分數'),
        ),
        migrations.AlterField(
            model_name='course_selection',
            name='studentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.student', verbose_name='學生'),
        ),
        migrations.AlterField(
            model_name='course_selection',
            name='week_1',
            field=models.BooleanField(verbose_name='第一周'),
        ),
    ]
