# Generated by Django 4.2.6 on 2023-11-30 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0035_alter_classroom_options_remove_classroom_seat_ip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_selection',
            name='score',
        ),
        migrations.RemoveField(
            model_name='course_selection',
            name='week_1',
        ),
    ]
