# Generated by Django 4.2.6 on 2023-12-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0036_remove_course_selection_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='studentID', max_length=128, verbose_name='密碼'),
        ),
    ]
