# Generated by Django 4.2.6 on 2023-12-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0038_alter_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_selection',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
